# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(max_length=250)),
                ('cat_name', models.CharField(max_length=500)),
                ('cat_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=250)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.category')),
            ],
        ),
    ]
