# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20170623_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='beverage_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=250)),
                ('recipe_name', models.CharField(max_length=500)),
                ('recipe_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='beverage_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=250)),
                ('ingredient2', models.CharField(max_length=250)),
                ('recipe_name', models.CharField(max_length=500)),
                ('recipe_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='beverage_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=250)),
                ('ingredient2', models.CharField(max_length=250)),
                ('ingredient3', models.CharField(max_length=250)),
                ('recipe_name', models.CharField(max_length=500)),
                ('recipe_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='beverage_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=250)),
                ('ingredient2', models.CharField(max_length=250)),
                ('ingredient3', models.CharField(max_length=250)),
                ('ingredient4', models.CharField(max_length=250)),
                ('recipe_name', models.CharField(max_length=500)),
                ('recipe_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='beverage_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=250)),
                ('ingredient2', models.CharField(max_length=250)),
                ('ingredient3', models.CharField(max_length=250)),
                ('ingredient4', models.CharField(max_length=250)),
                ('ingredient5', models.CharField(max_length=250)),
                ('recipe_name', models.CharField(max_length=500)),
                ('recipe_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
