# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_beverage_1_beverage_2_beverage_3_beverage_4_beverage_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desserts_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=20)),
                ('ingredient2', models.CharField(max_length=20)),
                ('ingredient3', models.CharField(max_length=20)),
                ('ingredient4', models.CharField(max_length=20)),
                ('ingredient5', models.CharField(max_length=20)),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Desserts_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=20)),
                ('ingredient2', models.CharField(max_length=20)),
                ('ingredient3', models.CharField(max_length=20)),
                ('ingredient4', models.CharField(max_length=20)),
                ('ingredient5', models.CharField(max_length=20)),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Desserts_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=20)),
                ('ingredient2', models.CharField(max_length=20)),
                ('ingredient3', models.CharField(max_length=20)),
                ('ingredient4', models.CharField(max_length=20)),
                ('ingredient5', models.CharField(max_length=20)),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Desserts_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=20)),
                ('ingredient2', models.CharField(max_length=20)),
                ('ingredient3', models.CharField(max_length=20)),
                ('ingredient4', models.CharField(max_length=20)),
                ('ingredient5', models.CharField(max_length=20)),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Desserts_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=20)),
                ('ingredient2', models.CharField(max_length=20)),
                ('ingredient3', models.CharField(max_length=20)),
                ('ingredient4', models.CharField(max_length=20)),
                ('ingredient5', models.CharField(max_length=20)),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_link', models.CharField(max_length=200)),
            ],
        ),
    ]
