# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_desserts_1_desserts_2_desserts_3_desserts_4_desserts_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desserts_1',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='desserts_1',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='desserts_1',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='desserts_1',
            name='ingredient5',
        ),
        migrations.RemoveField(
            model_name='desserts_2',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='desserts_2',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='desserts_2',
            name='ingredient5',
        ),
        migrations.RemoveField(
            model_name='desserts_3',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='desserts_3',
            name='ingredient5',
        ),
        migrations.RemoveField(
            model_name='desserts_4',
            name='ingredient5',
        ),
    ]
