# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_auto_20170626_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='welcome_beverage_1',
            new_name='beverage_1',
        ),
    ]
